// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CampaignController from "./campaign_controller"
application.register("campaign", CampaignController)

import CampaignDashboardController from "./campaign_dashboard_controller"
application.register("campaign-dashboard", CampaignDashboardController)

import FileManagerController from "./file_manager_controller"
application.register("file-manager", FileManagerController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import JourneyBuilderController from "./journey_builder_controller"
application.register("journey-builder", JourneyBuilderController)

import JourneyTemplatesController from "./journey_templates_controller"
application.register("journey-templates", JourneyTemplatesController)

import RichTextEditorController from "./rich_text_editor_controller"
application.register("rich-text-editor", RichTextEditorController)

import StageConfigController from "./stage_config_controller"
application.register("stage-config", StageConfigController)
