// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CampaignController from "./campaign_controller"
application.register("campaign", CampaignController)

import CampaignDashboardController from "./campaign_dashboard_controller"
application.register("campaign-dashboard", CampaignDashboardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
