import { metadata } from './layout'

// Mock next/font/google for layout tests
jest.mock('next/font/google', () => ({
  Geist: () => ({
    variable: '--font-geist-sans',
    className: 'geist-sans'
  }),
  Geist_Mono: () => ({
    variable: '--font-geist-mono', 
    className: 'geist-mono'
  })
}))

describe('RootLayout', () => {
  it('exports correct metadata', () => {
    expect(metadata.title).toBe('Create Next App')
    expect(metadata.description).toBe('Generated by create next app')
  })

  it('should have correct font configuration structure', async () => {
    // Test that layout module imports fonts correctly
    const layout = await import('./layout')
    expect(layout.default).toBeDefined()
    expect(layout.metadata).toBeDefined()
  })
})