# Sample credentials configuration for Active Storage cloud providers
# Copy this to configure your actual credentials with: bin/rails credentials:edit

# AWS S3 Configuration
aws:
  access_key_id: your_aws_access_key_id
  secret_access_key: your_aws_secret_access_key
  region: us-east-1  # or your preferred region
  bucket: marketer-gen-production  # or your bucket name
  # Optional: CloudFront CDN URL for faster delivery
  cloudfront_url: https://d123456789.cloudfront.net

# Google Cloud Storage Configuration  
gcs:
  project: your-gcs-project-id
  # Either provide credentials as JSON string or path to keyfile
  credentials: |
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "your-private-key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nyour-private-key\n-----END PRIVATE KEY-----\n",
      "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
      "client_id": "your-client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token"
    }
  bucket: marketer-gen-production

# Optional: Separate staging environment configurations
staging:
  aws:
    bucket: marketer-gen-staging
  gcs:
    bucket: marketer-gen-staging