# ETL Pipeline Configuration
# This file contains configuration for the ETL data processing pipeline

default: &default
  # Redis configuration for background jobs
  redis_url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>
  
  # Sidekiq configuration
  sidekiq_concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>
  sidekiq_queues:
    - etl_critical
    - etl_high_priority
    - etl_transformations
    - etl_data_pulls
    - etl_monitoring
    - etl_cleanup
    - default
    - low_priority
  
  # Data processing configuration
  batch_sizes:
    small: 100
    medium: 500
    large: 1000
    xl: 5000
  
  # Retry configuration
  retry_config:
    initial_delay: 2
    max_delay: 300
    multiplier: 2
    max_attempts: 5
  
  # Data source rate limits (requests per hour)
  rate_limits:
    google_analytics: 10000
    google_ads: 10000
    facebook_ads: 5000
    instagram_api: 5000
    twitter_api: 5000
    linkedin_api: 5000
    mailchimp: 10000
    hubspot: 40000
    salesforce: 15000
  
  # Data freshness thresholds (in minutes)
  freshness_thresholds:
    google_analytics: 60    # Hourly updates expected
    social_media: 5         # Real-time updates expected
    email_platforms: 60     # Hourly updates expected
    crm_systems: 1440       # Daily updates expected
  
  # Pipeline health monitoring
  health_monitoring:
    check_interval_minutes: 10
    error_rate_threshold: 10.0  # Percentage
    success_rate_threshold: 90.0 # Percentage
    max_queue_depth: 1000
    slow_job_threshold_minutes: 30
  
  # Data compression settings
  compression:
    enabled: true
    threshold_size_mb: 1
    algorithm: "zlib"  # Options: zlib, gzip
    level: 6          # Compression level 1-9
  
  # Data validation settings
  validation:
    max_error_rate: 0.1  # 10% of records can fail validation
    required_fields:
      - timestamp
      - source
      - platform
    
  # Alerting configuration
  alerts:
    enabled: true
    channels:
      - email
      - slack
      - log
    critical_threshold: 5   # Number of failures before critical alert
    warning_threshold: 3    # Number of failures before warning alert

development:
  <<: *default
  # Development-specific overrides
  sidekiq_concurrency: 2
  health_monitoring:
    check_interval_minutes: 30  # Less frequent checks in development
  rate_limits:
    google_analytics: 1000     # Lower limits for development
    google_ads: 1000
    facebook_ads: 500
  alerts:
    enabled: false             # Disable alerts in development

test:
  <<: *default
  # Test-specific overrides
  redis_url: 'redis://localhost:6379/1'  # Use different Redis DB for tests
  sidekiq_concurrency: 1
  health_monitoring:
    check_interval_minutes: 60
  rate_limits:
    google_analytics: 100      # Very low limits for testing
    google_ads: 100
    facebook_ads: 50
  alerts:
    enabled: false             # Disable alerts in test environment
  validation:
    max_error_rate: 0.5        # More lenient in tests

production:
  <<: *default
  # Production-specific configuration
  sidekiq_concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 20) %>
  
  # Production rate limits (per hour)
  rate_limits:
    google_analytics: <%= ENV.fetch('GA_RATE_LIMIT', 100000) %>
    google_ads: <%= ENV.fetch('GADS_RATE_LIMIT', 50000) %>
    facebook_ads: <%= ENV.fetch('FB_RATE_LIMIT', 25000) %>
    instagram_api: <%= ENV.fetch('IG_RATE_LIMIT', 25000) %>
    twitter_api: <%= ENV.fetch('TWITTER_RATE_LIMIT', 25000) %>
    linkedin_api: <%= ENV.fetch('LINKEDIN_RATE_LIMIT', 25000) %>
    mailchimp: <%= ENV.fetch('MAILCHIMP_RATE_LIMIT', 50000) %>
    hubspot: <%= ENV.fetch('HUBSPOT_RATE_LIMIT', 100000) %>
    salesforce: <%= ENV.fetch('SALESFORCE_RATE_LIMIT', 50000) %>
  
  # Production health monitoring
  health_monitoring:
    check_interval_minutes: 5   # More frequent checks in production
    error_rate_threshold: 5.0   # Stricter error rate threshold
    success_rate_threshold: 95.0 # Higher success rate expected
  
  # Production alerting
  alerts:
    enabled: true
    slack_webhook_url: <%= ENV.fetch('SLACK_WEBHOOK_URL', '') %>
    email_recipients: <%= ENV.fetch('ALERT_EMAIL_RECIPIENTS', '').split(',') %>
    critical_threshold: 3       # Faster critical alerts
    warning_threshold: 2        # Faster warning alerts
  
  # Production validation (stricter)
  validation:
    max_error_rate: 0.05        # Only 5% of records can fail validation