# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  
  # Activity monitoring jobs
  activity_cleanup:
    class: ActivityCleanupJob
    schedule: every day at 2am
    description: "Clean up old activity logs older than retention period"
  
  daily_activity_report:
    command: "ActivityReportService.generate_daily_reports"
    schedule: every day at 8am
    description: "Generate and send daily activity reports to admins"
  
  hourly_security_scan:
    command: "SuspiciousActivityDetector.scan_all_users"
    schedule: every hour
    description: "Scan for suspicious activity patterns"

development:
  # Development environment recurring jobs
  activity_cleanup:
    class: ActivityCleanupJob
    schedule: every 6 hours
    description: "Clean up old activity logs in development"
