# ETL Pipeline Scheduled Jobs
# These jobs run automatically to pull data from various sources

# High-frequency data pulls (every 5 minutes)
social_media_realtime_sync:
  cron: "*/5 * * * *"
  class: "Etl::SocialMediaRealTimeJob"
  queue: "etl_high_priority"
  description: "Pull real-time social media metrics"

# Standard frequency data pulls (hourly)
google_analytics_hourly:
  cron: "0 * * * *"
  class: "Etl::GoogleAnalyticsHourlyJob"
  queue: "etl_data_pulls"
  description: "Pull Google Analytics data hourly"

email_metrics_hourly:
  cron: "15 * * * *"
  class: "Etl::EmailMetricsHourlyJob"
  queue: "etl_data_pulls"
  description: "Pull email platform metrics hourly"

# Daily comprehensive pulls
google_analytics_daily:
  cron: "0 1 * * *"
  class: "Etl::GoogleAnalyticsDailyJob"
  queue: "etl_data_pulls"
  description: "Daily comprehensive Google Analytics pull"

crm_daily_sync:
  cron: "0 2 * * *"
  class: "Etl::CrmDailySyncJob"
  queue: "etl_data_pulls"
  description: "Daily CRM data synchronization"

social_media_daily_reports:
  cron: "0 3 * * *"
  class: "Etl::SocialMediaDailyReportsJob"
  queue: "etl_data_pulls"
  description: "Daily social media comprehensive reports"

email_campaign_daily_analysis:
  cron: "0 4 * * *"
  class: "Etl::EmailCampaignDailyAnalysisJob"
  queue: "etl_data_pulls"
  description: "Daily email campaign analysis"

# Data transformation and normalization
data_normalization_daily:
  cron: "0 5 * * *"
  class: "Etl::DataNormalizationJob"
  queue: "etl_transformations"
  description: "Daily data normalization across all platforms"

attribution_modeling_daily:
  cron: "0 6 * * *"
  class: "Etl::AttributionModelingJob"
  queue: "etl_transformations"
  description: "Daily attribution modeling calculations"

# Weekly comprehensive analysis
weekly_data_quality_audit:
  cron: "0 7 * * 0"
  class: "Etl::DataQualityAuditJob"
  queue: "etl_monitoring"
  description: "Weekly data quality audit and cleanup"

weekly_performance_optimization:
  cron: "0 8 * * 0"
  class: "Etl::PerformanceOptimizationJob"
  queue: "etl_monitoring"
  description: "Weekly ETL performance optimization"

# Cleanup and maintenance
data_compression_daily:
  cron: "0 23 * * *"
  class: "Etl::DataCompressionJob"
  queue: "etl_cleanup"
  description: "Daily data compression for large datasets"

pipeline_health_monitoring:
  cron: "*/10 * * * *"
  class: "Etl::PipelineHealthMonitorJob"
  queue: "etl_monitoring"
  description: "ETL pipeline health monitoring every 10 minutes"

# Monthly archival and optimization
monthly_data_archival:
  cron: "0 0 1 * *"
  class: "Etl::MonthlyDataArchivalJob"
  queue: "etl_cleanup"
  description: "Monthly data archival and cleanup"

# Error recovery and retry management
failed_jobs_recovery:
  cron: "*/30 * * * *"
  class: "Etl::FailedJobsRecoveryJob"
  queue: "etl_monitoring"
  description: "Check and retry failed ETL jobs every 30 minutes"