default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 600
  workers:
    - queues: "default"
      threads: 3
      processes: 1
    - queues: "ai_generation"
      threads: 2
      processes: 1
      polling_interval: 5
    - queues: "webhooks"
      threads: 5
      processes: 1
      polling_interval: 2

development:
  <<: *default
  workers:
    - queues: "default"
      threads: 2
      processes: 1
    - queues: "ai_generation"
      threads: 1
      processes: 1
      polling_interval: 5
    - queues: "webhooks"
      threads: 2
      processes: 1
      polling_interval: 2

test:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      processes: 1

production:
  <<: *default
  workers:
    - queues: "default"
      threads: 5
      processes: 2
    - queues: "ai_generation"
      threads: 3
      processes: 2
      polling_interval: 5
    - queues: "webhooks"
      threads: 8
      processes: 1
      polling_interval: 2